// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/bug/ent/list"
	"entgo.io/bug/ent/settings"
	"entgo.io/bug/ent/user"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SettingsCreate is the builder for creating a Settings entity.
type SettingsCreate struct {
	config
	mutation *SettingsMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (sc *SettingsCreate) SetUserID(i int) *SettingsCreate {
	sc.mutation.SetUserID(i)
	return sc
}

// SetListID sets the "list_id" field.
func (sc *SettingsCreate) SetListID(i int) *SettingsCreate {
	sc.mutation.SetListID(i)
	return sc
}

// SetTest sets the "test" field.
func (sc *SettingsCreate) SetTest(s string) *SettingsCreate {
	sc.mutation.SetTest(s)
	return sc
}

// SetList sets the "list" edge to the List entity.
func (sc *SettingsCreate) SetList(l *List) *SettingsCreate {
	return sc.SetListID(l.ID)
}

// SetUser sets the "user" edge to the User entity.
func (sc *SettingsCreate) SetUser(u *User) *SettingsCreate {
	return sc.SetUserID(u.ID)
}

// Mutation returns the SettingsMutation object of the builder.
func (sc *SettingsCreate) Mutation() *SettingsMutation {
	return sc.mutation
}

// Save creates the Settings in the database.
func (sc *SettingsCreate) Save(ctx context.Context) (*Settings, error) {
	var (
		err  error
		node *Settings
	)
	if len(sc.hooks) == 0 {
		if err = sc.check(); err != nil {
			return nil, err
		}
		node, err = sc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*SettingsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = sc.check(); err != nil {
				return nil, err
			}
			sc.mutation = mutation
			if node, err = sc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(sc.hooks) - 1; i >= 0; i-- {
			if sc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = sc.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, sc.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Settings)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from SettingsMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (sc *SettingsCreate) SaveX(ctx context.Context) *Settings {
	v, err := sc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (sc *SettingsCreate) Exec(ctx context.Context) error {
	_, err := sc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (sc *SettingsCreate) ExecX(ctx context.Context) {
	if err := sc.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (sc *SettingsCreate) check() error {
	if _, ok := sc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "Settings.user_id"`)}
	}
	if _, ok := sc.mutation.ListID(); !ok {
		return &ValidationError{Name: "list_id", err: errors.New(`ent: missing required field "Settings.list_id"`)}
	}
	if _, ok := sc.mutation.Test(); !ok {
		return &ValidationError{Name: "test", err: errors.New(`ent: missing required field "Settings.test"`)}
	}
	if _, ok := sc.mutation.ListID(); !ok {
		return &ValidationError{Name: "list", err: errors.New(`ent: missing required edge "Settings.list"`)}
	}
	if _, ok := sc.mutation.UserID(); !ok {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "Settings.user"`)}
	}
	return nil
}

func (sc *SettingsCreate) sqlSave(ctx context.Context) (*Settings, error) {
	_node, _spec := sc.createSpec()
	if err := sqlgraph.CreateNode(ctx, sc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (sc *SettingsCreate) createSpec() (*Settings, *sqlgraph.CreateSpec) {
	var (
		_node = &Settings{config: sc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: settings.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: settings.FieldID,
			},
		}
	)
	_spec.OnConflict = sc.conflict
	if value, ok := sc.mutation.Test(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: settings.FieldTest,
		})
		_node.Test = value
	}
	if nodes := sc.mutation.ListIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   settings.ListTable,
			Columns: []string{settings.ListColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: list.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ListID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := sc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   settings.UserTable,
			Columns: []string{settings.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Settings.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SettingsUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
//
func (sc *SettingsCreate) OnConflict(opts ...sql.ConflictOption) *SettingsUpsertOne {
	sc.conflict = opts
	return &SettingsUpsertOne{
		create: sc,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Settings.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (sc *SettingsCreate) OnConflictColumns(columns ...string) *SettingsUpsertOne {
	sc.conflict = append(sc.conflict, sql.ConflictColumns(columns...))
	return &SettingsUpsertOne{
		create: sc,
	}
}

type (
	// SettingsUpsertOne is the builder for "upsert"-ing
	//  one Settings node.
	SettingsUpsertOne struct {
		create *SettingsCreate
	}

	// SettingsUpsert is the "OnConflict" setter.
	SettingsUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *SettingsUpsert) SetUserID(v int) *SettingsUpsert {
	u.Set(settings.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SettingsUpsert) UpdateUserID() *SettingsUpsert {
	u.SetExcluded(settings.FieldUserID)
	return u
}

// SetListID sets the "list_id" field.
func (u *SettingsUpsert) SetListID(v int) *SettingsUpsert {
	u.Set(settings.FieldListID, v)
	return u
}

// UpdateListID sets the "list_id" field to the value that was provided on create.
func (u *SettingsUpsert) UpdateListID() *SettingsUpsert {
	u.SetExcluded(settings.FieldListID)
	return u
}

// SetTest sets the "test" field.
func (u *SettingsUpsert) SetTest(v string) *SettingsUpsert {
	u.Set(settings.FieldTest, v)
	return u
}

// UpdateTest sets the "test" field to the value that was provided on create.
func (u *SettingsUpsert) UpdateTest() *SettingsUpsert {
	u.SetExcluded(settings.FieldTest)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Settings.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *SettingsUpsertOne) UpdateNewValues() *SettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//  client.Settings.Create().
//      OnConflict(sql.ResolveWithIgnore()).
//      Exec(ctx)
//
func (u *SettingsUpsertOne) Ignore() *SettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SettingsUpsertOne) DoNothing() *SettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SettingsCreate.OnConflict
// documentation for more info.
func (u *SettingsUpsertOne) Update(set func(*SettingsUpsert)) *SettingsUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SettingsUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *SettingsUpsertOne) SetUserID(v int) *SettingsUpsertOne {
	return u.Update(func(s *SettingsUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SettingsUpsertOne) UpdateUserID() *SettingsUpsertOne {
	return u.Update(func(s *SettingsUpsert) {
		s.UpdateUserID()
	})
}

// SetListID sets the "list_id" field.
func (u *SettingsUpsertOne) SetListID(v int) *SettingsUpsertOne {
	return u.Update(func(s *SettingsUpsert) {
		s.SetListID(v)
	})
}

// UpdateListID sets the "list_id" field to the value that was provided on create.
func (u *SettingsUpsertOne) UpdateListID() *SettingsUpsertOne {
	return u.Update(func(s *SettingsUpsert) {
		s.UpdateListID()
	})
}

// SetTest sets the "test" field.
func (u *SettingsUpsertOne) SetTest(v string) *SettingsUpsertOne {
	return u.Update(func(s *SettingsUpsert) {
		s.SetTest(v)
	})
}

// UpdateTest sets the "test" field to the value that was provided on create.
func (u *SettingsUpsertOne) UpdateTest() *SettingsUpsertOne {
	return u.Update(func(s *SettingsUpsert) {
		s.UpdateTest()
	})
}

// Exec executes the query.
func (u *SettingsUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SettingsCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SettingsUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SettingsUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SettingsUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SettingsCreateBulk is the builder for creating many Settings entities in bulk.
type SettingsCreateBulk struct {
	config
	builders []*SettingsCreate
	conflict []sql.ConflictOption
}

// Save creates the Settings entities in the database.
func (scb *SettingsCreateBulk) Save(ctx context.Context) ([]*Settings, error) {
	specs := make([]*sqlgraph.CreateSpec, len(scb.builders))
	nodes := make([]*Settings, len(scb.builders))
	mutators := make([]Mutator, len(scb.builders))
	for i := range scb.builders {
		func(i int, root context.Context) {
			builder := scb.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SettingsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, scb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = scb.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, scb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, scb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (scb *SettingsCreateBulk) SaveX(ctx context.Context) []*Settings {
	v, err := scb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (scb *SettingsCreateBulk) Exec(ctx context.Context) error {
	_, err := scb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (scb *SettingsCreateBulk) ExecX(ctx context.Context) {
	if err := scb.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Settings.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SettingsUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
//
func (scb *SettingsCreateBulk) OnConflict(opts ...sql.ConflictOption) *SettingsUpsertBulk {
	scb.conflict = opts
	return &SettingsUpsertBulk{
		create: scb,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Settings.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
//
func (scb *SettingsCreateBulk) OnConflictColumns(columns ...string) *SettingsUpsertBulk {
	scb.conflict = append(scb.conflict, sql.ConflictColumns(columns...))
	return &SettingsUpsertBulk{
		create: scb,
	}
}

// SettingsUpsertBulk is the builder for "upsert"-ing
// a bulk of Settings nodes.
type SettingsUpsertBulk struct {
	create *SettingsCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Settings.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
//
func (u *SettingsUpsertBulk) UpdateNewValues() *SettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Settings.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
//
func (u *SettingsUpsertBulk) Ignore() *SettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SettingsUpsertBulk) DoNothing() *SettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SettingsCreateBulk.OnConflict
// documentation for more info.
func (u *SettingsUpsertBulk) Update(set func(*SettingsUpsert)) *SettingsUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SettingsUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *SettingsUpsertBulk) SetUserID(v int) *SettingsUpsertBulk {
	return u.Update(func(s *SettingsUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SettingsUpsertBulk) UpdateUserID() *SettingsUpsertBulk {
	return u.Update(func(s *SettingsUpsert) {
		s.UpdateUserID()
	})
}

// SetListID sets the "list_id" field.
func (u *SettingsUpsertBulk) SetListID(v int) *SettingsUpsertBulk {
	return u.Update(func(s *SettingsUpsert) {
		s.SetListID(v)
	})
}

// UpdateListID sets the "list_id" field to the value that was provided on create.
func (u *SettingsUpsertBulk) UpdateListID() *SettingsUpsertBulk {
	return u.Update(func(s *SettingsUpsert) {
		s.UpdateListID()
	})
}

// SetTest sets the "test" field.
func (u *SettingsUpsertBulk) SetTest(v string) *SettingsUpsertBulk {
	return u.Update(func(s *SettingsUpsert) {
		s.SetTest(v)
	})
}

// UpdateTest sets the "test" field to the value that was provided on create.
func (u *SettingsUpsertBulk) UpdateTest() *SettingsUpsertBulk {
	return u.Update(func(s *SettingsUpsert) {
		s.UpdateTest()
	})
}

// Exec executes the query.
func (u *SettingsUpsertBulk) Exec(ctx context.Context) error {
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SettingsCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SettingsCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SettingsUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
