// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// List is the predicate function for list builders.
type List func(*sql.Selector)

// Settings is the predicate function for settings builders.
type Settings func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
